# set default lc
export LC_ALL=en_US.UTF-8

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(
    alias-finder
    colorize
    fzf
    history
    kubectl
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# used to help learn aliases
alias a="alias-finder"
alias al="alias-finder -l"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
